 #application-prod.yml 开发环境配置文件
 #application-dev.yml 测试环境配置文件

 #指定配置文件
# spring:
#   profiles:
#     active: dev

server:
  port: 8080
  context-path: /girl
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/girl
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update

