#配置端口和路径前缀
server:
  port: 8080
  #context-path: /girl
#配置参数 罩杯,年龄。 添加前缀girl。 可以使用类来装载配置文件。 使用了分组就不能在配置文件中调用组内的参数。
girl:
  cupSize:  b
  age:      18
  #内容：在配置文件中使用参数调用参数
  content:  "cupSize: ${cupSize}, age: ${age}"

  ####################################################################################################
  #application-dev.yml 测试环境配置文件
